version: '3.7'
networks:
  cloudasr_clasr-net:
    external: true
services:
  reverseproxy:
    image: smartcommunitylab/reverseproxy:parallel1
    ports:
      - 80:80
      - 8001:8001
      - 8000:8000
      - 8080:8080
      - 443:443
    networks:
      - cloudasr_clasr-net
    volumes:
      - ~/cloud-asr/cloudasr/reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - ~/cert:/etc/nginx/cert
    deploy:
      placement:
        constraints: [node.labels.task == manager]
